### ISSUE TITLE
Problem with query param at the end of url

### ISSUE THREAD

**Issue by vmenard** [alakarteio/roadhog-saga#32]
Hi guys @fabienjuif @guillaumecrespel ,
I try to add query parameter at the end of my url but it's not formatted correctly
`yield call(roadhog('GET_TOTO'), { path: [webappId, 'tata'], query: { myquery: "titi"} })`
I would like this url : toto/1234/tata?myquery=titi 
but I have : toto/1234/tata/?myquery=titi 
/ is added after tata

https://github.com/alakarteio/roadhog-saga/blob/13727d396fbff4227aeaac725c8b0501bfcc46dd/src/url-pattern/addQueryParams.js#L9

**Comment by fabienjuif** [comment]
Can you open a PR ?
With maybe a thing like that:
```js
  const slash = (params.length > 0 /* ADDED */ || url.endsWith('/') || url.endsWith('&') || url.endsWith('?')) ? '' : '/'
  const questionMark = (url.endsWith('&') || url.endsWith('?')) ? '' : '?'

  return `${url}${slash}${questionMark}${params.join('&')}`
```

**Comment by vmenard** [comment]
@fabienjuif , Ok but I don't have the rights to push :(

**Comment by fabienjuif** [comment]
fixe by #33 

@vmenard do you need this ASAP ?
Should I publish ?

**Comment by vmenard** [comment]
@fabienjuif Yes I need it  :) thanks

**Comment by fabienjuif** [comment]
@vmenard  `+ roadhog-saga@3.0.4`
